/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GameInput = IDL.Record({
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'trending' : IDL.Bool,
  'coverImage' : IDL.Opt(ExternalBlob),
  'sport' : IDL.Text,
  'franchise' : IDL.Text,
  'genre' : IDL.Text,
  'isNew' : IDL.Bool,
  'releaseYear' : IDL.Nat,
  'developer' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'gameId' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const UserProfileView = IDL.Record({
  'favorites' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'playCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'recentlyPlayed' : IDL.Vec(IDL.Text),
});
export const Game = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'trending' : IDL.Bool,
  'playCount' : IDL.Nat,
  'coverImage' : IDL.Opt(ExternalBlob),
  'sport' : IDL.Text,
  'franchise' : IDL.Text,
  'genre' : IDL.Text,
  'rating' : IDL.Float64,
  'isNew' : IDL.Bool,
  'releaseYear' : IDL.Nat,
  'developer' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGame' : IDL.Func([GameInput], [IDL.Text], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteGame' : IDL.Func([IDL.Text], [], []),
  'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGame' : IDL.Func([IDL.Text], [Game], ['query']),
  'getGameComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getGameRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'playGame' : IDL.Func([IDL.Text], [], []),
  'rateGame' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
  'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateFavorites' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateGame' : IDL.Func([IDL.Text, GameInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GameInput = IDL.Record({
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'trending' : IDL.Bool,
    'coverImage' : IDL.Opt(ExternalBlob),
    'sport' : IDL.Text,
    'franchise' : IDL.Text,
    'genre' : IDL.Text,
    'isNew' : IDL.Bool,
    'releaseYear' : IDL.Nat,
    'developer' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'gameId' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const UserProfileView = IDL.Record({
    'favorites' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'playCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'recentlyPlayed' : IDL.Vec(IDL.Text),
  });
  const Game = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'trending' : IDL.Bool,
    'playCount' : IDL.Nat,
    'coverImage' : IDL.Opt(ExternalBlob),
    'sport' : IDL.Text,
    'franchise' : IDL.Text,
    'genre' : IDL.Text,
    'rating' : IDL.Float64,
    'isNew' : IDL.Bool,
    'releaseYear' : IDL.Nat,
    'developer' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGame' : IDL.Func([GameInput], [IDL.Text], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteGame' : IDL.Func([IDL.Text], [], []),
    'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGame' : IDL.Func([IDL.Text], [Game], ['query']),
    'getGameComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getGameRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'playGame' : IDL.Func([IDL.Text], [], []),
    'rateGame' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
    'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateFavorites' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateGame' : IDL.Func([IDL.Text, GameInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };