/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'gameId' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Game {
  'id' : string,
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'platform' : string,
  'trending' : boolean,
  'playCount' : bigint,
  'coverImage' : [] | [ExternalBlob],
  'sport' : string,
  'franchise' : string,
  'genre' : string,
  'rating' : number,
  'isNew' : boolean,
  'releaseYear' : bigint,
  'developer' : string,
}
export interface GameInput {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'platform' : string,
  'trending' : boolean,
  'coverImage' : [] | [ExternalBlob],
  'sport' : string,
  'franchise' : string,
  'genre' : string,
  'isNew' : boolean,
  'releaseYear' : bigint,
  'developer' : string,
}
export interface UserProfileView {
  'favorites' : Array<string>,
  'name' : string,
  'playCounts' : Array<[string, bigint]>,
  'recentlyPlayed' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGame' : ActorMethod<[GameInput], string>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteGame' : ActorMethod<[string], undefined>,
  'getAllComments' : ActorMethod<[], Array<Comment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGame' : ActorMethod<[string], Game>,
  'getGameComments' : ActorMethod<[string], Array<Comment>>,
  'getGameRating' : ActorMethod<[string], number>,
  'getLeaderboard' : ActorMethod<[bigint], Array<[Principal, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listGames' : ActorMethod<[], Array<Game>>,
  'playGame' : ActorMethod<[string], undefined>,
  'rateGame' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'updateComment' : ActorMethod<[bigint, string], undefined>,
  'updateFavorites' : ActorMethod<[string, boolean], undefined>,
  'updateGame' : ActorMethod<[string, GameInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];